---
title: "checklist_creation_soortenmeetnetten"
author: "Dimitri Brosens"
date: "2024-08-01"
output: html_document
---

# create species lists based on files that includes headers already

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries:

```{r}
library(tidyverse)      # To do data science
library(tidylog)        # To provide feedback on dplyr functions
library(magrittr)       # To use %<>% pipes
library(here)           # To find files
library(janitor)        # To clean input data
library(readxl)         # To read Excel files
library(digest)         # To generate hashes
library(rgbif)          # To use GBIF services
library(lubridate)      # to transform the date
library(mapview)
```

# Read source data

Create a data frame `input_data` from the source data:

```{r}
taxon <- read.delim2(here::here("datasets", "checklist_soortenmeetnetten", "data", "checklist_soortenmeetnetten.csv"), sep = ";")
```



Preview data:

```{r}
taxon %>% head(n = 5)
```
add kingdom

```{r}
taxon <- taxon %>% mutate(kingdom = case_when(taxon$taxongroep == "Vaatplanten" ~"Plantae",
                                              taxon$taxongroep == "Vogels" ~"Animalia",
                                              taxon$taxongroep == "Zoogdieren" ~"Animalia",
                                              taxon$taxongroep == "Kreeftachtigen" ~"Animalia",
                                              taxon$taxongroep == "Amfibieën" ~"Animalia",
                                              taxon$taxongroep == "Wespen" ~"Animalia",
                                              taxon$taxongroep == "Vissen" ~"Animalia",
                                              taxon$taxongroep == "Reptielen" ~"Animalia",
                                              taxon$taxongroep == "Platwormen" ~"Animalia",
                                              taxon$taxongroep == "Wieren" ~"Plantae",
                                              taxon$taxongroep == "Mieren" ~"Animalia",
                                              taxon$taxongroep == "Weekdieren" ~"Animalia",
                                              taxon$taxongroep == "Dagvlinders" ~"Animalia",
                                              taxon$taxongroep == "Libellen" ~"Animalia",
                                              taxon$taxongroep == "Nachtvlinders" ~"Animalia",
                                              taxon$taxongroep == "Spinnen" ~"Animalia",
                                              taxon$taxongroep == "Kevers" ~"Animalia",
                                              taxon$taxongroep == "Sprinkhanen" ~"Animalia",
                                              taxon$taxongroep == "Saproxyle kevers" ~"Animalia",
                                              taxon$taxongroep == "Bladmossen" ~"Plantae",
                                              taxon$taxongroep == "Korstmossen" ~"Plantae"
                                              ))
```
add some informative columns



# listname

```{r}
taxon %<>% mutate(listName = "checklist Meetnetten")
```





rename certain columns (quick DwC mapping)

```{r}
taxon <- taxon %>% rename(
  "scientificName" = "NaamWet_interpretatie",
  "scientificNameAuthorship" = "Auteur",
  "vernacularName" = "NaamNed_interpretatie",
  "taxonListGroup" = "taxonlijstgroep",
  "YearOfPublication" = "PublicatieJaar",
  "list" = "Lijst",
  "attributeValue" = "Kenmerkwaarde",
  "attribute" = "Kenmerk"    
  
)
```




remove obsolete columns

```{r}
taxon <- taxon %>% select(
                        -"NaamNed",
                        -"LaatsteVersie",
                        -"NaamWet")
 
```

```{r}
taxon <- distinct(taxon, .keep_all = FALSE)
```



```{r}
write_csv(taxon, here::here("datasets", "checklist_soortenmeetnetten", "data", "processed", "vbp_checklist_meetnetten.csv"), na = "")
```

