---
title: "checklist_creation_natuurpunt_vbp"
author: "Dimitri Brosens"
date: "2024-08-01"
output: html_document
---

# create species lists based on files that includes headers already

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries:

```{r}
library(tidyverse)      # To do data science
library(tidylog)        # To provide feedback on dplyr functions
library(magrittr)       # To use %<>% pipes
library(here)           # To find files
library(janitor)        # To clean input data
library(readxl)         # To read Excel files
library(digest)         # To generate hashes
library(rgbif)          # To use GBIF services
library(lubridate)      # to transform the date
library(mapview)
```

# Read source data

Create a data frame `input_data` from the source data:

```{r}
taxon <- read.delim(here::here("datasets", "checklist_belgium_natuurpunt", "data", "raw", "taxon.txt"))
```

```{r}
distribution <- read.delim(here::here("datasets", "checklist_belgium_natuurpunt", "data", "raw", "distribution.txt"))
```


Preview data:

```{r}
taxon %>% head(n = 5)
```
```{r}
distribution %>% head(n = 5)
```

```{r}
distribution %>% head(n = 5)
```

# Join tables


```{r}
vbp_checklist_natuurpunt_belgium <- inner_join(taxon, distribution, by = 'taxonID')
```



```{r}
vbp_checklist_natuurpunt_belgium <- unique(vbp_checklist_natuurpunt_belgium)
```


```{r}
vbp_checklist_natuurpunt_belgium %>% head(n = 5)
```
remove obsolete columns

```{r eval=FALSE, include=FALSE}
vbp_checklist_natuurpunt_belgium <- vbp_checklist_natuurpunt_belgium %>% select(
                        -"kingdom...1",
                        -"scientificName...2",
                        -"occurrenceStatus.y")
 
```
rename certain columns

```{r eval=FALSE, include=FALSE}
vbp_checklist_natuurpunt_belgium <- vbp_checklist_natuurpunt_belgium %>% rename(
  "occurrenceStatus" = "occurrenceStatus.x",
  "scientificName" = "scientificName...15",
  "kingdom" = "kingdom...20"
  
)
```

```{r}

vbp_checklist_natuurpunt_belgium_animalia <- vbp_checklist_natuurpunt_belgium %>% filter(vbp_checklist_natuurpunt_belgium$kingdom == 'Animalia',
                                                                                         vbp_checklist_natuurpunt_belgium$locality == 'Flemish Region')                                                                                    

```




```{r}

vbp_checklist_natuurpunt_belgium_plantae <- vbp_checklist_natuurpunt_belgium %>% filter(vbp_checklist_natuurpunt_belgium$kingdom == 'Plantae',
                                                                                        vbp_checklist_natuurpunt_belgium$locality == 'Flemish Region')

```


```{r}
write_csv(vbp_checklist_natuurpunt_belgium_animalia, here::here("datasets", "checklist_belgium_natuurpunt", "data", "processed", "vbp_checklist_natuurpunt_belgium_animalia.csv"), na = "")
```


```{r}
write_csv(vbp_checklist_natuurpunt_belgium_plantae, here::here("datasets", "checklist_belgium_natuurpunt", "data", "processed", "vbp_checklist_natuurpunt_belgium_plantae.csv"), na = "")
```

