---
title: "checklist_creation_alien_molluscs"
author: "Dimitri Brosens"
date: "2024-08-01"
output: html_document
---

# create species lists based on files that includes headers already

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries:

```{r}
library(tidyverse)      # To do data science
library(tidylog)        # To provide feedback on dplyr functions
library(magrittr)       # To use %<>% pipes
library(here)           # To find files
library(janitor)        # To clean input data
library(readxl)         # To read Excel files
library(digest)         # To generate hashes
library(rgbif)          # To use GBIF services
library(lubridate)      # to transform the date
library(mapview)
```

# Read source data

Create a data frame `input_data` from the source data:

```{r}
taxon <- read.delim("https://raw.githubusercontent.com/trias-project/alien-mollusca-checklist/refs/heads/master/data/processed/taxon.tsv")
```

```{r}
distribution <- read.delim("https://raw.githubusercontent.com/trias-project/alien-mollusca-checklist/refs/heads/master/data/processed/distribution.tsv")
```

```{r}
description <- read.delim("https://raw.githubusercontent.com/trias-project/alien-mollusca-checklist/refs/heads/master/data/processed/description.tsv")
```

```{r}
speciesprofile <- read.delim("https://raw.githubusercontent.com/trias-project/alien-mollusca-checklist/refs/heads/master/data/processed/speciesprofile.tsv")
```

```{r}
vernacularname <- read.delim("https://raw.githubusercontent.com/trias-project/alien-mollusca-checklist/refs/heads/master/data/processed/vernacularname.tsv")
```

```{r}
references <- read.delim("https://raw.githubusercontent.com/trias-project/alien-mollusca-checklist/refs/heads/master/data/processed/references.tsv")
```


Preview data:

```{r}
taxon %>% head(n = 5)
```
```{r}
description %>% head(n = 5)
```

```{r}
distribution %>% head(n = 5)
```
```{r}
speciesprofile %>% head(n = 5)
```
```{r}
vernacularname %>% head(n = 5)
```

# Join tables


```{r}
interim_molluscs_alien_a <- left_join(taxon, distribution, description, by = 'taxonID')
```

```{r}
interim_molluscs_alien_b <- left_join(interim_molluscs_alien_a, speciesprofile,  by = 'taxonID')
```


```{r}
interim_molluscs_alien <- left_join(interim_molluscs_alien_b, vernacularname, references,  by = 'taxonID')
```


```{r}
vbp_molluscs_alien <- unique(interim_molluscs_alien)
```

remove obsolete columns

```{r}
interim_molluscs_alien <- interim_molluscs_alien %>% select(
                        -"language.x")
 
```
rename certain columns

```{r}
interim_molluscs_alien <- interim_molluscs_alien %>% rename(
  "language" = "language.y")
```

```{r}
write_csv(vbp_molluscs_alien, here::here("datasets", "checklist_introduced_terrestrial_molluscs_belgium", "data", "processed", "vbp_molluscs_alien.csv"), na = "")
```

