---
title: "checklist_creation_vbp soortenbesluit "
author: "Dimitri Brosens"
date: "2024-08-01"
output: html_document
---

# create species lists based on files that includes headers already

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries:

```{r}
library(tidyverse)      # To do data science
library(tidylog)        # To provide feedback on dplyr functions
library(magrittr)       # To use %<>% pipes
library(here)           # To find files
library(janitor)        # To clean input data
library(readxl)         # To read Excel files
library(digest)         # To generate hashes
library(rgbif)          # To use GBIF services
library(lubridate)      # to transform the date
library(mapview)
```

# Read source data

Create a data frame `input_data` from the source data:

```{r}
taxon_core <- read.delim(here::here("datasets", "soortenbesluit", "data", "raw", "soortenbesluit.csv"), sep = ";")
```


Preview data:

```{r}
taxon_core %>% head(n = 5)
```


remove obsolete columns

```{r}
taxon_core <- taxon_core %>% select(
                        ##-"KenmerkCode",
                        -"Kenmerk",
                        -"taxonlijstgroep"
                        )
 
```
# Map to Darwin Core

# Fixed terms

```{r}
taxon_core <- taxon_core %>%
  mutate(
    dwc_license              = paste0("http://creativecommons.org/publicdomain",
                                      "/zero/1.0/"),
    dwc_datasetName         = "Soortenbesluit",
    dwc_kingdom              = "Animalia",
    dwc_stateProvince        = "Flanders",
    dwc_countryCode          = "BE",
    dwc_kenmerkwaarde   = Kenmerkwaarde ,
    dwc_status =       paste("Wettelijk bepaald: ", KenmerkwaardeCode)
  )
```

# mapped terms

```{r}
taxon_core <- taxon_core %>%
  mutate(
    "dwc_vernacularName"    = NaamNed,
    #"dwc_kingdom" = case_when(taxon_core$taxongroep == 'Vaatplanten' ~ "Plantae",
    #                          TRUE ~ as.character('Animalia')),
    "dwc_scientificName"   = NaamWet_interpretatie ,
    "dwc_vernacularName"   = NaamNed_interpretatie ,
    "dwc_scientificNameAuthorship" = Auteur ,
    "dwc_kenmerkwaardecode" = KenmerkwaardeCode,
    #"dwc_taxonlistgroup" = taxonlijstgroep ,
    
  )
```

## Post-processing

Only keep the Darwin Core columns:

```{r}
taxon_core %<>% select(starts_with("dwc_"))
```

Drop the `dwc_` prefix:

```{r}
colnames(taxon_core ) <- str_remove(colnames(taxon_core ), "dwc_")
```

Preview data:

```{r}
taxon_core  %>% head()
```
```{r}
taxon_core_cat5 <- taxon_core %>%
  filter(kenmerkwaardecode == "cat5") %>%
  distinct()
```


```{r}
taxon_core_cat4 <- taxon_core %>%
  filter(kenmerkwaardecode == "cat4") %>%
  distinct()
```

```{r}
taxon_core_cat3 <- taxon_core %>%
  filter(kenmerkwaardecode == "cat3") %>%
  distinct()
```
```{r}
taxon_core_cat2 <- taxon_core %>%
  filter(kenmerkwaardecode == "cat2") %>%
  distinct()
```
```{r}
taxon_core_cat1 <- taxon_core %>%
  filter(kenmerkwaardecode == "cat1") %>%
  distinct()
```

```{r}
write_csv(taxon_core, here::here("datasets", "soortenbesluit", "data", "processed", "vbp_soortenbesluit.csv"), na = "")
```


```{r}
write_csv(taxon_core_cat1, here::here("datasets", "soortenbesluit", "data", "processed", "vbp_soortenbesluitcat1.csv"), na = "")
```

```{r}
write_csv(taxon_core_cat2, here::here("datasets", "soortenbesluit", "data", "processed", "vbp_soortenbesluitcat2.csv"), na = "")
```

```{r}
write_csv(taxon_core_cat3, here::here("datasets", "soortenbesluit", "data", "processed", "vbp_soortenbesluitcat3.csv"), na = "")
```

```{r}
write_csv(taxon_core_cat4, here::here("datasets", "soortenbesluit", "data", "processed", "vbp_soortenbesluitcat4.csv"), na = "")
```


```{r}
write_csv(taxon_core_cat5, here::here("datasets", "soortenbesluit", "data", "processed", "vbp_soortenbesluitcat5.csv"), na = "")
```


